export type RelatedRefs = {
  sessionId?: string | null;
  turnId?: string | null;
  foregroundRunId?: string | null;
  plannerRunId?: string | null;
  planId?: string | null;
  planStepId?: string | null;
  workflowId?: string | null;
  workflowRunId?: string | null;
  workflowStepId?: string | null;
  workflowStepRunId?: string | null;
  kernelRunId?: string | null;
  backgroundRunId?: string | null;
  subagentRunId?: string | null;
  toolCallId?: string | null;
  approvalId?: string | null;
  triggerId?: string | null;
  waitConditionId?: string | null;
  artifactId?: string | null;
  memoryId?: string | null;
  summaryId?: string | null;
  auditId?: string | null;
};
