/**
 * SearchSubagent tool contract and scope guardrails.
 *
 * This module defines the structured evidence fields for the search_subagent tool
 * and enforces that SearchSubagent can only call search-category tools.
 */

import type { WebSearchResultItem } from './types.js'

/**
 * Search intent classification for query planning.
 */
export type SearchIntent = 'weather' | 'news' | 'technical' | 'product' | 'local' | 'general'

/**
 * Query plan generated by the search subagent before execution.
 * Captures the original user question and the planned search strategy.
 */
export interface SearchQueryPlan {
  /** The original user question before transformation */
  originalQuestion: string

  /** The search query that will be sent to the search provider */
  searchQuery: string

  /** Classified intent of the search (weather, news, technical, etc.) */
  intent: SearchIntent

  /** Whether the query requires fresh/recent results (e.g., news, weather) */
  requiresFreshness: boolean

  /** Optional locale for location-aware searches (e.g., 'en-US', 'de-DE') */
  locale?: string

  /** Critical context that is missing and may affect result quality */
  missingCriticalContext: string[]
}

/**
 * Extracted fact from search results.
 * Represents a single piece of information extracted from search results.
 */
export interface ExtractedFact {
  /** The extracted fact text */
  fact: string

  /** Source URL where the fact was found */
  sourceUrl: string

  /** Confidence level of the extraction (0-1) */
  confidence: number

  /** Optional relevance score to the original query */
  relevanceScore?: number
}

/**
 * Warning generated during search execution.
 */
export interface SearchWarning {
  /** Warning code for programmatic handling */
  code: string

  /** Human-readable warning message */
  message: string

  /** Whether the warning is recoverable */
  recoverable: boolean
}

/**
 * Metadata for the search subagent tool result.
 */
export interface SearchSubagentMetadata {
  /** Duration of the search in milliseconds */
  durationMs: number

  /** Number of results returned */
  resultCount: number

  /** Number of unique sources (domains) in results */
  uniqueSourceCount: number
}

/**
 * Structured evidence result from the search_subagent tool.
 *
 * This is the tool contract output - it contains structured evidence
 * for downstream processing, NOT a final answer for the user.
 *
 * IMPORTANT: This interface does NOT include a finalAnswer or userVisibleResponse
 * field because search_subagent is a tool, not a responder. The Foreground Kernel
 * is responsible for synthesizing the final user-visible response.
 */
export interface SearchSubagentToolResult {
  /** The original user question */
  originalQuestion: string

  /** The search query that was executed */
  searchQuery: string

  /** Classified intent of the search */
  intent: SearchIntent

  /** Whether the query required fresh results */
  freshness: boolean

  /** Optional locale used for the search */
  locale?: string

  /** Search result items from the provider */
  results: WebSearchResultItem[]

  /** Facts extracted from search results */
  extractedFacts: ExtractedFact[]

  /** Warnings generated during execution */
  warnings: SearchWarning[]

  /** Execution metadata */
  metadata: SearchSubagentMetadata

  /** The query plan that was executed */
  queryPlan: SearchQueryPlan
}

/**
 * Tool IDs that are allowed for SearchSubagent to call.
 * These are the only tools in the 'search' category.
 */
export const SEARCH_CATEGORY_TOOL_IDS = ['web_search', 'docs_search'] as const

/**
 * Type for valid search category tool IDs.
 */
export type SearchCategoryToolId = (typeof SEARCH_CATEGORY_TOOL_IDS)[number]

/**
 * Error code for non-search tool scope violations.
 */
export const NON_SEARCH_TOOL_NOT_ALLOWED = 'NON_SEARCH_TOOL_NOT_ALLOWED' as const

/**
 * Error thrown when SearchSubagent attempts to call a non-search tool.
 *
 * This is a scope guardrail to prevent SearchSubagent from calling
 * arbitrary tools like foreground_spawn_planner, file_read, etc.
 */
export class SearchSubagentScopeError extends Error {
  public readonly code = NON_SEARCH_TOOL_NOT_ALLOWED
  public readonly toolId: string
  public readonly allowedTools: readonly SearchCategoryToolId[]

  constructor(toolId: string) {
    super(`SearchSubagent cannot call tool '${toolId}'. ` + `Allowed tools: ${SEARCH_CATEGORY_TOOL_IDS.join(', ')}`)
    this.name = 'SearchSubagentScopeError'
    this.toolId = toolId
    this.allowedTools = SEARCH_CATEGORY_TOOL_IDS

    // Maintains proper stack trace for where error was thrown (V8 engines)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, SearchSubagentScopeError)
    }
  }
}

/**
 * Assert that a tool ID is allowed for SearchSubagent.
 * Throws SearchSubagentScopeError if the tool ID is not in the search category.
 *
 * @param toolId - The tool ID to validate
 * @throws SearchSubagentScopeError if toolId is not a search category tool
 */
export function assertSearchScope(toolId: string): asserts toolId is SearchCategoryToolId {
  const isValid = SEARCH_CATEGORY_TOOL_IDS.includes(toolId as SearchCategoryToolId)

  if (!isValid) {
    throw new SearchSubagentScopeError(toolId)
  }
}

/**
 * Check if a tool ID is allowed for SearchSubagent without throwing.
 *
 * @param toolId - The tool ID to check
 * @returns true if the tool ID is in the search category
 */
export function isSearchCategoryTool(toolId: string): toolId is SearchCategoryToolId {
  return SEARCH_CATEGORY_TOOL_IDS.includes(toolId as SearchCategoryToolId)
}
