/**
 * SearchSubagent tool contract and scope guardrails.
 *
 * This module defines the structured evidence fields for the search_subagent tool
 * and enforces that SearchSubagent can only call search-category tools.
 */

import type { WebSearchResultItem } from './types.js'
import type { SearchRoundStopReason } from './search-round-evaluator.js'

/**
 * Round stop reason union, defined canonically by the pure round evaluator
 * (`SEARCH_ROUND_STOP_REASONS` as const). Re-exported here so observability
 * consumers share ONE literal union instead of duplicating it.
 */
export type { SearchRoundStopReason }

/**
 * Search intent classification for query planning.
 */
export type SearchIntent = 'weather' | 'news' | 'technical' | 'product' | 'local' | 'general'

/**
 * Query plan generated by the search subagent before execution.
 * Captures the original user question and the planned search strategy.
 */
export interface SearchQueryPlan {
  /** The original user question before transformation */
  originalQuestion: string

  /** The search query that will be sent to the search provider */
  searchQuery: string

  /** Classified intent of the search (weather, news, technical, etc.) */
  intent: SearchIntent

  /** Whether the query requires fresh/recent results (e.g., news, weather) */
  requiresFreshness: boolean

  /** Optional locale for location-aware searches (e.g., 'en-US', 'de-DE') */
  locale?: string

  /** Critical context that is missing and may affect result quality */
  missingCriticalContext: string[]
}

/**
 * Typed search plan hints propagated from the parent `SearchQueryPlan` into a
 * search child task. Persisted inside `task_spec_json` (no schema migration);
 * parsed back at the persisted-task boundary with backward-compatible fallback
 * for old task specs (objective as originalQuestion, general intent, no
 * optional fields). Generic kernel adapter paths ignore the field entirely.
 */
export interface SearchPlanHints {
  /** The original user question before transformation. */
  originalQuestion: string
  /** Classified intent of the search. */
  intent: SearchIntent
  /** Whether the query requires fresh/recent results (mirrors `SearchQueryPlan.requiresFreshness`). */
  freshness?: boolean
  /** Optional locale for location-aware searches. */
  locale?: string
  /** Critical context missing from the question (replan hint / public partial signal only). */
  missingCriticalContext?: readonly string[]
}

const SEARCH_INTENTS: readonly SearchIntent[] = ['weather', 'news', 'technical', 'product', 'local', 'general']

/** Loose persisted shape of `SearchPlanHints` — every field is validated independently. */
interface SearchPlanHintsCandidate {
  originalQuestion?: unknown
  intent?: unknown
  freshness?: unknown
  locale?: unknown
  missingCriticalContext?: unknown
}

function isHintsCandidate(value: unknown): value is SearchPlanHintsCandidate {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isSearchIntent(value: unknown): value is SearchIntent {
  return typeof value === 'string' && SEARCH_INTENTS.includes(value as SearchIntent)
}

/**
 * Typed parser/normalizer for persisted search plan hints at the persisted-task
 * boundary. Old/missing/malformed payloads never throw: `originalQuestion`
 * falls back to the task objective, `intent` to 'general', and invalid optional
 * fields are omitted.
 *
 * @param raw - The value persisted in `task_spec_json.searchPlanHints` (unknown at runtime).
 * @param objective - The child task objective used as the originalQuestion fallback.
 */
export function parseSearchPlanHints(raw: unknown, objective = ''): SearchPlanHints {
  const source = isHintsCandidate(raw) ? raw : undefined

  const originalQuestion =
    source !== undefined && typeof source.originalQuestion === 'string' && source.originalQuestion.trim().length > 0
      ? source.originalQuestion
      : objective

  const intent = source !== undefined && isSearchIntent(source.intent) ? source.intent : 'general'

  const hints: SearchPlanHints = { originalQuestion, intent }

  if (source !== undefined && typeof source.freshness === 'boolean') {
    hints.freshness = source.freshness
  }
  if (source !== undefined && typeof source.locale === 'string' && source.locale.length > 0) {
    hints.locale = source.locale
  }
  if (source !== undefined && Array.isArray(source.missingCriticalContext)) {
    hints.missingCriticalContext = source.missingCriticalContext.filter(
      (entry): entry is string => typeof entry === 'string',
    )
  }

  return hints
}

/**
 * Extracted fact from search results.
 * Represents a single piece of information extracted from search results.
 */
export interface ExtractedFact {
  /** The extracted fact text */
  fact: string

  /** Source URL where the fact was found */
  sourceUrl: string

  /** Confidence level of the extraction (0-1) */
  confidence: number

  /** Optional relevance score to the original query */
  relevanceScore?: number

  /** Optional source title where the fact was found */
  sourceTitle?: string

  /** Optional source rank after result selection */
  sourceRank?: number
}

export type EvidenceSufficiency = 'sufficient' | 'partial' | 'insufficient'

/**
 * Warning generated during search execution.
 */
export interface SearchWarning {
  /** Warning code for programmatic handling */
  code: string

  /** Human-readable warning message */
  message: string

  /** Whether the warning is recoverable */
  recoverable: boolean
}

/**
 * Metadata for the search subagent tool result.
 */
export interface SearchSubagentMetadata {
  durationMs: number
  resultCount: number
  uniqueSourceCount: number
  rankingVersion?: string
  sourceQualityVersion?: string
  evidenceSufficiency?: EvidenceSufficiency
  searchCallCount?: number
  agentProfile?: string
  /** Optional child-session task ID when the search ran inside a resumable child session (additive). */
  taskId?: string
  /** Number of completed search rounds (multi-round executions only; absent for default one-round). */
  roundCount?: number
  /** Number of replan (round >= 2) phase-1 calls (multi-round executions only). */
  replanCount?: number
  /** Number of LLM complete() invocations scheduled, including forced->auto attempts. */
  llmCallCount?: number
  /** Why the search loop stopped (multi-round executions only). */
  stopReason?: SearchRoundStopReason
  /** True when the round/completion budget was exhausted (multi-round executions only). */
  budgetExhausted?: boolean
}

/**
 * Structured evidence result from the search_subagent tool.
 *
 * This is the tool contract output - it contains structured evidence
 * for downstream processing, NOT a final answer for the user.
 *
 * IMPORTANT: This interface does NOT include a finalAnswer or userVisibleResponse
 * field because search_subagent is a tool, not a responder. The Foreground Kernel
 * is responsible for synthesizing the final user-visible response.
 */
export interface SearchSubagentToolResult {
  /** The original user question */
  originalQuestion: string

  /** The search query that was executed */
  searchQuery: string

  /** Classified intent of the search */
  intent: SearchIntent

  /** Whether the query required fresh results */
  freshness: boolean

  /** Optional locale used for the search */
  locale?: string

  /** Search result items from the provider */
  results: WebSearchResultItem[]

  /** Facts extracted from search results */
  extractedFacts: ExtractedFact[]

  /** Warnings generated during execution */
  warnings: SearchWarning[]

  /** Execution metadata */
  metadata: SearchSubagentMetadata

  /** The query plan that was executed */
  queryPlan: SearchQueryPlan
}

/**
 * Tool IDs that are allowed for SearchSubagent to call.
 * These are the only tools in the 'search' category.
 */
export const SEARCH_CATEGORY_TOOL_IDS = ['web_search', 'docs_search'] as const

/**
 * Type for valid search category tool IDs.
 */
export type SearchCategoryToolId = (typeof SEARCH_CATEGORY_TOOL_IDS)[number]

/**
 * Error code for non-search tool scope violations.
 */
export const NON_SEARCH_TOOL_NOT_ALLOWED = 'NON_SEARCH_TOOL_NOT_ALLOWED' as const

/**
 * Error thrown when SearchSubagent attempts to call a non-search tool.
 *
 * This is a scope guardrail to prevent SearchSubagent from calling
 * arbitrary tools like foreground_spawn_planner, file_read, etc.
 */
export class SearchSubagentScopeError extends Error {
  public readonly code = NON_SEARCH_TOOL_NOT_ALLOWED
  public readonly toolId: string
  public readonly allowedTools: readonly SearchCategoryToolId[]

  constructor(toolId: string) {
    super(`SearchSubagent cannot call tool '${toolId}'. ` + `Allowed tools: ${SEARCH_CATEGORY_TOOL_IDS.join(', ')}`)
    this.name = 'SearchSubagentScopeError'
    this.toolId = toolId
    this.allowedTools = SEARCH_CATEGORY_TOOL_IDS

    // Maintains proper stack trace for where error was thrown (V8 engines)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, SearchSubagentScopeError)
    }
  }
}

/**
 * Assert that a tool ID is allowed for SearchSubagent.
 * Throws SearchSubagentScopeError if the tool ID is not in the search category.
 *
 * @param toolId - The tool ID to validate
 * @throws SearchSubagentScopeError if toolId is not a search category tool
 */
export function assertSearchScope(toolId: string): asserts toolId is SearchCategoryToolId {
  const isValid = SEARCH_CATEGORY_TOOL_IDS.includes(toolId as SearchCategoryToolId)

  if (!isValid) {
    throw new SearchSubagentScopeError(toolId)
  }
}

/**
 * Check if a tool ID is allowed for SearchSubagent without throwing.
 *
 * @param toolId - The tool ID to check
 * @returns true if the tool ID is in the search category
 */
export function isSearchCategoryTool(toolId: string): toolId is SearchCategoryToolId {
  return SEARCH_CATEGORY_TOOL_IDS.includes(toolId as SearchCategoryToolId)
}
