import type { ConnectionManager } from './connection.js'

/**
 * Preview generation status for file uploads.
 */
export type FilePreviewStatus = 'pending' | 'generated' | 'skipped' | 'failed'

/**
 * Sensitivity classification for file uploads.
 */
export type FileSensitivity = 'low' | 'medium' | 'high' | 'restricted'

/**
 * Lifecycle status for file uploads.
 */
export type FileUploadStatus = 'uploading' | 'ready' | 'deleted'

/**
 * Metadata record for a user-uploaded file.
 * Raw bytes are stored externally via storageRef; only metadata lives in DB.
 */
export interface FileUploadRecord {
  fileId: string
  userId: string
  sessionId: string
  tenantId: string
  originalFilename: string
  sanitizedName: string
  mimeType: string
  extension: string
  sizeBytes: number
  checksum: string
  storageRef: string
  previewText: string | undefined
  previewStatus: FilePreviewStatus
  sensitivity: FileSensitivity
  status: FileUploadStatus
  createdAt: string
  updatedAt: string
  deletedAt: string | undefined
}

/**
 * Input for creating a new file upload record.
 * fileId, createdAt, updatedAt are generated by the store.
 */
export type FileUploadCreateInput = Omit<FileUploadRecord, 'fileId' | 'createdAt' | 'updatedAt' | 'deletedAt'>

/**
 * Fields that may be updated on an existing file upload record.
 */
export interface FileUploadUpdateInput {
  originalFilename?: string
  sanitizedName?: string
  mimeType?: string
  extension?: string
  sizeBytes?: number
  checksum?: string
  storageRef?: string
  previewText?: string
  previewStatus?: FilePreviewStatus
  sensitivity?: FileSensitivity
  status?: FileUploadStatus
}

/**
 * Accessor context for ownership checks.
 */
export interface FileUploadAccessor {
  userId?: string
  sessionId?: string
}

/**
 * Pagination options for list queries.
 */
export interface FileUploadListOptions {
  limit?: number
  offset?: number
}

/**
 * Store interface for file upload metadata CRUD operations.
 */
export interface FileUploadStore {
  /** Create a new file upload record. Returns the stored record with generated id/timestamps. */
  create(data: FileUploadCreateInput): FileUploadRecord
  /** Retrieve a file record by id. Enforces ownership: accessor must match userId or sessionId. */
  getById(fileId: string, accessor: FileUploadAccessor): FileUploadRecord | undefined
  /** List file records for a given session, ordered by creation time descending. */
  listBySession(sessionId: string, options?: FileUploadListOptions): FileUploadRecord[]
  /** List file records for a given user, ordered by creation time descending. */
  listByUser(userId: string, options?: FileUploadListOptions): FileUploadRecord[]
  /** Update mutable fields on an existing file record. Returns updated record or undefined if not found. */
  update(fileId: string, data: FileUploadUpdateInput): FileUploadRecord | undefined
  /** Soft delete: sets status='deleted' and deletedAt=now. Returns true if updated. */
  markDeleted(fileId: string): boolean
  /** Hard delete: removes the record entirely. Returns true if deleted. */
  delete(fileId: string): boolean
}

// ── Internal row type (snake_case DB columns) ──────────────────────────────

interface FileUploadRow {
  file_id: string
  user_id: string
  session_id: string
  tenant_id: string
  original_filename: string
  sanitized_name: string
  mime_type: string
  extension: string
  size_bytes: number
  checksum: string
  storage_ref: string
  preview_text: string | null
  preview_status: FilePreviewStatus
  sensitivity: FileSensitivity
  status: FileUploadStatus
  created_at: string
  updated_at: string
  deleted_at: string | null
}

// ── Implementation ─────────────────────────────────────────────────────────

class FileUploadStoreImpl implements FileUploadStore {
  private connection: ConnectionManager

  constructor(connection: ConnectionManager) {
    this.connection = connection
  }

  create(data: FileUploadCreateInput): FileUploadRecord {
    const fileId = crypto.randomUUID()
    const now = new Date().toISOString()

    this.connection.exec(
      `INSERT INTO file_uploads (
        file_id, user_id, session_id, tenant_id,
        original_filename, sanitized_name, mime_type, extension,
        size_bytes, checksum, storage_ref,
        preview_text, preview_status, sensitivity, status,
        created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        fileId,
        data.userId,
        data.sessionId,
        data.tenantId,
        data.originalFilename,
        data.sanitizedName,
        data.mimeType,
        data.extension,
        data.sizeBytes,
        data.checksum,
        data.storageRef,
        data.previewText ?? null,
        data.previewStatus,
        data.sensitivity,
        data.status,
        now,
        now,
      ],
    )

    return {
      fileId,
      userId: data.userId,
      sessionId: data.sessionId,
      tenantId: data.tenantId,
      originalFilename: data.originalFilename,
      sanitizedName: data.sanitizedName,
      mimeType: data.mimeType,
      extension: data.extension,
      sizeBytes: data.sizeBytes,
      checksum: data.checksum,
      storageRef: data.storageRef,
      previewText: data.previewText,
      previewStatus: data.previewStatus,
      sensitivity: data.sensitivity,
      status: data.status,
      createdAt: now,
      updatedAt: now,
      deletedAt: undefined,
    }
  }

  getById(fileId: string, accessor: FileUploadAccessor): FileUploadRecord | undefined {
    const rows = this.connection.query<FileUploadRow>(
      'SELECT * FROM file_uploads WHERE file_id = ?',
      [fileId],
    )

    if (rows.length === 0) {
      return undefined
    }

    const record = this.mapRow(rows[0]!)

    // Enforce ownership: accessor must match userId OR sessionId
    if (accessor.userId && record.userId === accessor.userId) {
      return record
    }
    if (accessor.sessionId && record.sessionId === accessor.sessionId) {
      return record
    }
    // If no accessor provided, deny access
    if (!accessor.userId && !accessor.sessionId) {
      return undefined
    }

    return undefined
  }

  listBySession(sessionId: string, options: FileUploadListOptions = {}): FileUploadRecord[] {
    const { limit = 100, offset = 0 } = options
    const rows = this.connection.query<FileUploadRow>(
      'SELECT * FROM file_uploads WHERE session_id = ? AND status != ? ORDER BY created_at DESC LIMIT ? OFFSET ?',
      [sessionId, 'deleted', limit, offset],
    )
    return rows.map((row) => this.mapRow(row))
  }

  listByUser(userId: string, options: FileUploadListOptions = {}): FileUploadRecord[] {
    const { limit = 100, offset = 0 } = options
    const rows = this.connection.query<FileUploadRow>(
      'SELECT * FROM file_uploads WHERE user_id = ? AND status != ? ORDER BY created_at DESC LIMIT ? OFFSET ?',
      [userId, 'deleted', limit, offset],
    )
    return rows.map((row) => this.mapRow(row))
  }

  update(fileId: string, data: FileUploadUpdateInput): FileUploadRecord | undefined {
    const existing = this.findById(fileId)
    if (!existing) {
      return undefined
    }

    const updates: string[] = []
    const values: unknown[] = []

    if (data.originalFilename !== undefined) {
      updates.push('original_filename = ?')
      values.push(data.originalFilename)
    }
    if (data.sanitizedName !== undefined) {
      updates.push('sanitized_name = ?')
      values.push(data.sanitizedName)
    }
    if (data.mimeType !== undefined) {
      updates.push('mime_type = ?')
      values.push(data.mimeType)
    }
    if (data.extension !== undefined) {
      updates.push('extension = ?')
      values.push(data.extension)
    }
    if (data.sizeBytes !== undefined) {
      updates.push('size_bytes = ?')
      values.push(data.sizeBytes)
    }
    if (data.checksum !== undefined) {
      updates.push('checksum = ?')
      values.push(data.checksum)
    }
    if (data.storageRef !== undefined) {
      updates.push('storage_ref = ?')
      values.push(data.storageRef)
    }
    if (data.previewText !== undefined) {
      updates.push('preview_text = ?')
      values.push(data.previewText)
    }
    if (data.previewStatus !== undefined) {
      updates.push('preview_status = ?')
      values.push(data.previewStatus)
    }
    if (data.sensitivity !== undefined) {
      updates.push('sensitivity = ?')
      values.push(data.sensitivity)
    }
    if (data.status !== undefined) {
      updates.push('status = ?')
      values.push(data.status)
    }

    if (updates.length === 0) {
      return existing
    }

    const updatedAt = new Date().toISOString()
    updates.push('updated_at = ?')
    values.push(updatedAt)
    values.push(fileId)

    this.connection.exec(`UPDATE file_uploads SET ${updates.join(', ')} WHERE file_id = ?`, values)

    return this.findById(fileId)
  }

  markDeleted(fileId: string): boolean {
    const now = new Date().toISOString()
    this.connection.exec(
      "UPDATE file_uploads SET status = 'deleted', deleted_at = ?, updated_at = ? WHERE file_id = ?",
      [now, now, fileId],
    )
    const rows = this.connection.query<FileUploadRow>(
      'SELECT * FROM file_uploads WHERE file_id = ?',
      [fileId],
    )
    return rows.length > 0 && rows[0]!.status === 'deleted'
  }

  delete(fileId: string): boolean {
    this.connection.exec('DELETE FROM file_uploads WHERE file_id = ?', [fileId])
    const rows = this.connection.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM file_uploads WHERE file_id = ?',
      [fileId],
    )
    return rows[0]?.count === 0
  }

  // ── Private helpers ────────────────────────────────────────────────────

  private findById(fileId: string): FileUploadRecord | undefined {
    const rows = this.connection.query<FileUploadRow>(
      'SELECT * FROM file_uploads WHERE file_id = ?',
      [fileId],
    )
    if (rows.length === 0) {
      return undefined
    }
    return this.mapRow(rows[0]!)
  }

  private mapRow(row: FileUploadRow): FileUploadRecord {
    return {
      fileId: row.file_id,
      userId: row.user_id,
      sessionId: row.session_id,
      tenantId: row.tenant_id,
      originalFilename: row.original_filename,
      sanitizedName: row.sanitized_name,
      mimeType: row.mime_type,
      extension: row.extension,
      sizeBytes: row.size_bytes,
      checksum: row.checksum,
      storageRef: row.storage_ref,
      previewText: row.preview_text ?? undefined,
      previewStatus: row.preview_status,
      sensitivity: row.sensitivity,
      status: row.status,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
      deletedAt: row.deleted_at ?? undefined,
    }
  }
}

/**
 * Factory function for creating a FileUploadStore instance.
 */
export function createFileUploadStore(connection: ConnectionManager): FileUploadStore {
  return new FileUploadStoreImpl(connection)
}
