/**
 * SqlDialect — SQL dialect abstraction for SQLite vs PostgreSQL differences.
 *
 * Provides ready-to-use SQL fragments that differ between database engines.
 * Instances are immutable and created via static factory methods.
 *
 * @example
 * const dialect = SqlDialect.sqlite();
 * dialect.jsonExtract('data', '$.name'); // "json_extract(data, '$.name')"
 *
 * const pg = SqlDialect.postgresql();
 * pg.jsonExtract('data', '$.name'); // "data->>'name'"
 */
export class SqlDialect {
  readonly type: 'sqlite' | 'postgresql'

  private constructor(type: 'sqlite' | 'postgresql') {
    this.type = type
  }

  /** Create a SQLite dialect instance. */
  static sqlite(): SqlDialect {
    return Object.freeze(new SqlDialect('sqlite')) as SqlDialect
  }

  /** Create a PostgreSQL dialect instance. */
  static postgresql(): SqlDialect {
    return Object.freeze(new SqlDialect('postgresql')) as SqlDialect
  }

  // ─── JSON Operations ──────────────────────────────────────────────

  /**
   * Extract a value from a JSON column.
   *
   * SQLite: `json_extract(col, '$.path')`
   * PostgreSQL: `col->>'path'`
   *
   * @example
   * sqlite.jsonExtract('data', '$.name')   // "json_extract(data, '$.name')"
   * pg.jsonExtract('data', '$.name')        // "data->>'name'"
   */
  jsonExtract(column: string, path: string): string {
    if (this.type === 'sqlite') {
      return `json_extract(${column}, '${path}')`
    }
    // Convert JSON path '$.key' or '$.key.nested' to PostgreSQL path syntax
    const pgPath = this.toPostgresPath(path)
    return `${column}->>'${pgPath}'`
  }

  /**
   * Set a value in a JSON column.
   *
   * SQLite: `json_set(col, '$.path', val)`
   * PostgreSQL: `jsonb_set(col::jsonb, '{path}', to_jsonb(val))`
   *
   * @example
   * sqlite.jsonSet('data', '$.name', "'Alice'")  // "json_set(data, '$.name', 'Alice')"
   * pg.jsonSet('data', '$.name', "'Alice'")       // "jsonb_set(data::jsonb, '{name}', to_jsonb('Alice'))"
   */
  jsonSet(column: string, path: string, value: string): string {
    if (this.type === 'sqlite') {
      return `json_set(${column}, '${path}', ${value})`
    }
    const pgPath = this.toPostgresPathArray(path)
    return `jsonb_set(${column}::jsonb, '${pgPath}', to_jsonb(${value}))`
  }

  /**
   * Expand a JSON array into a set of rows.
   *
   * SQLite: `json_each(col)`
   * PostgreSQL: `jsonb_array_elements(col)`
   *
   * @example
   * sqlite.jsonEach('tags')   // "json_each(tags)"
   * pg.jsonEach('tags')       // "jsonb_array_elements(tags)"
   */
  jsonEach(column: string): string {
    if (this.type === 'sqlite') {
      return `json_each(${column})`
    }
    return `jsonb_array_elements(${column})`
  }

  // ─── Date/Time Functions ──────────────────────────────────────────

  /**
   * Current date/time function.
   *
   * SQLite: `datetime('now')`
   * PostgreSQL: `NOW()`
   *
   * @example
   * sqlite.now()   // "datetime('now')"
   * pg.now()       // "NOW()"
   */
  now(): string {
    if (this.type === 'sqlite') {
      return "datetime('now')"
    }
    return 'NOW()'
  }

  /**
   * Current timestamp expression.
   *
   * Both: `CURRENT_TIMESTAMP`
   *
   * @example
   * dialect.currentTimestamp() // "CURRENT_TIMESTAMP"
   */
  currentTimestamp(): string {
    return 'CURRENT_TIMESTAMP'
  }

  /**
   * Add an interval to a datetime column or expression.
   *
   * SQLite: `datetime(col, '+1 day')`
   * PostgreSQL: `col + INTERVAL '1 day'`
   *
   * @example
   * sqlite.datetimeAdd('created_at', 1, 'day')   // "datetime(created_at, '+1 day')"
   * pg.datetimeAdd('created_at', 1, 'day')        // "created_at + INTERVAL '1 day'"
   */
  datetimeAdd(column: string, amount: number, unit: string): string {
    if (this.type === 'sqlite') {
      return `datetime(${column}, '+${amount} ${unit}')`
    }
    return `${column} + INTERVAL '${amount} ${unit}'`
  }

  // ─── DDL Helpers ──────────────────────────────────────────────────

  /**
   * Auto-increment column modifier.
   *
   * SQLite: `AUTOINCREMENT`
   * PostgreSQL: `GENERATED BY DEFAULT AS IDENTITY`
   *
   * @example
   * sqlite.autoIncrement()   // "AUTOINCREMENT"
   * pg.autoIncrement()       // "GENERATED BY DEFAULT AS IDENTITY"
   */
  autoIncrement(): string {
    if (this.type === 'sqlite') {
      return 'AUTOINCREMENT'
    }
    return 'GENERATED BY DEFAULT AS IDENTITY'
  }

  /**
   * Text column type.
   *
   * Both: `TEXT`
   *
   * @example
   * dialect.textType() // "TEXT"
   */
  textType(): string {
    return 'TEXT'
  }

  /**
   * JSON column type.
   *
   * SQLite: `TEXT` (JSON stored as text)
   * PostgreSQL: `JSONB`
   *
   * @example
   * sqlite.jsonType()   // "TEXT"
   * pg.jsonType()       // "JSONB"
   */
  jsonType(): string {
    if (this.type === 'sqlite') {
      return 'TEXT'
    }
    return 'JSONB'
  }

  /**
   * Boolean column type.
   *
   * SQLite: `INTEGER` (0/1 representation)
   * PostgreSQL: `BOOLEAN`
   *
   * @example
   * sqlite.booleanType()   // "INTEGER"
   * pg.booleanType()       // "BOOLEAN"
   */
  booleanType(): string {
    if (this.type === 'sqlite') {
      return 'INTEGER'
    }
    return 'BOOLEAN'
  }

  // ─── Full-Text Search ─────────────────────────────────────────────

  /**
   * Create a full-text search table.
   *
   * SQLite: `CREATE VIRTUAL TABLE tableName USING fts5(col1, col2, content=contentTable)`
   * PostgreSQL: `CREATE MATERIALIZED VIEW tableName AS SELECT ...` (placeholder — pg_trgm or tsvector recommended)
   *
   * @example
   * sqlite.createFtsTable('search_idx', ['title', 'body'], 'articles')
   * // "CREATE VIRTUAL TABLE search_idx USING fts5(title, body, content=articles)"
   *
   * pg.createFtsTable('search_idx', ['title', 'body'])
   * // "CREATE MATERIALIZED VIEW search_idx AS SELECT title, body FROM articles"
   */
  createFtsTable(tableName: string, columns: string[], contentTable?: string): string {
    if (this.type === 'sqlite') {
      const contentClause = contentTable ? `, content=${contentTable}` : ''
      return `CREATE VIRTUAL TABLE ${tableName} USING fts5(${columns.join(', ')}${contentClause})`
    }
    const source = contentTable ?? tableName
    const colList = columns.join(', ')
    return `CREATE MATERIALIZED VIEW ${tableName} AS SELECT ${colList} FROM ${source}`
  }

  // ─── Index Helpers ────────────────────────────────────────────────

  /**
   * Create an index on a JSON path.
   *
   * SQLite: `CREATE INDEX idx ON table(json_extract(col, '$.path'))`
   * PostgreSQL: `CREATE INDEX idx ON table USING GIN(col jsonb_path_ops)`
   *
   * @example
   * sqlite.createJsonIndex('users', 'profile', '$.email')
   * // "CREATE INDEX idx_users_profile ON users(json_extract(profile, '$.email'))"
   *
   * pg.createJsonIndex('users', 'profile', '$.email')
   * // "CREATE INDEX idx_users_profile ON users USING GIN(profile jsonb_path_ops)"
   */
  createJsonIndex(table: string, column: string, jsonPath: string): string {
    const indexName = `idx_${table}_${column}`
    if (this.type === 'sqlite') {
      return `CREATE INDEX ${indexName} ON ${table}(json_extract(${column}, '${jsonPath}'))`
    }
    return `CREATE INDEX ${indexName} ON ${table} USING GIN(${column} jsonb_path_ops)`
  }

  // ─── Query Helpers ────────────────────────────────────────────────

  /**
   * LIMIT/OFFSET clause with parameterized placeholders.
   *
   * SQLite: `LIMIT ? OFFSET ?`
   * PostgreSQL: `LIMIT $n OFFSET $m`
   *
   * @example
   * sqlite.limitOffset(10, 20)   // "LIMIT ? OFFSET ?"
   * pg.limitOffset(10, 20)       // "LIMIT $1 OFFSET $2"
   */
  limitOffset(_limit: number, offset?: number): string {
    if (this.type === 'sqlite') {
      if (offset !== undefined) {
        return 'LIMIT ? OFFSET ?'
      }
      return 'LIMIT ?'
    }
    if (offset !== undefined) {
      return `LIMIT $1 OFFSET $2`
    }
    return 'LIMIT $1'
  }

  /**
   * Parameter placeholder for prepared statements.
   *
   * SQLite: always `?` (index ignored)
   * PostgreSQL: `$1`, `$2`, etc. (1-indexed)
   *
   * @example
   * sqlite.parameterize(0)   // "?"
   * sqlite.parameterize(5)   // "?"
   * pg.parameterize(1)       // "$1"
   * pg.parameterize(3)       // "$3"
   */
  parameterize(index: number): string {
    if (this.type === 'sqlite') {
      return '?'
    }
    return `$${index}`
  }

  /**
   * Case-insensitive LIKE operator.
   *
   * SQLite: `LIKE` (case-insensitive for ASCII by default)
   * PostgreSQL: `ILIKE`
   *
   * @example
   * sqlite.ilike()   // "LIKE"
   * pg.ilike()       // "ILIKE"
   */
  ilike(): string {
    if (this.type === 'sqlite') {
      return 'LIKE'
    }
    return 'ILIKE'
  }

  /**
   * Boolean TRUE literal.
   *
   * SQLite: `1`
   * PostgreSQL: `TRUE`
   *
   * @example
   * sqlite.trueLiteral()   // "1"
   * pg.trueLiteral()       // "TRUE"
   */
  trueLiteral(): string {
    if (this.type === 'sqlite') {
      return '1'
    }
    return 'TRUE'
  }

  /**
   * Boolean FALSE literal.
   *
   * SQLite: `0`
   * PostgreSQL: `FALSE`
   *
   * @example
   * sqlite.falseLiteral()   // "0"
   * pg.falseLiteral()       // "FALSE"
   */
  falseLiteral(): string {
    if (this.type === 'sqlite') {
      return '0'
    }
    return 'FALSE'
  }

  // ─── Internal Helpers ─────────────────────────────────────────────

  /**
   * Convert a JSON path like '$.name' or '$.address.city' to a PostgreSQL
   * arrow-operator path like 'name' or 'address'->>'city'.
   * For single-level paths, returns the key directly.
   * For multi-level paths, returns the first key (caller can chain ->>).
   */
  private toPostgresPath(jsonPath: string): string {
    // Strip leading '$.' or '$'
    const stripped = jsonPath.startsWith('$.') ? jsonPath.slice(2) : jsonPath.replace(/^\$/, '')
    // For simple paths, return the last key for ->>
    const parts = stripped.split('.')
    return parts[parts.length - 1]
  }

  /**
   * Convert a JSON path like '$.name' to PostgreSQL array literal '{name}'.
   * For nested paths like '$.address.city', returns '{address,city}'.
   */
  private toPostgresPathArray(jsonPath: string): string {
    const stripped = jsonPath.startsWith('$.') ? jsonPath.slice(2) : jsonPath.replace(/^\$/, '')
    const parts = stripped.split('.')
    return `{${parts.join(',')}}`
  }
}
