import { describe, it, expect } from 'vitest';
import { SqlDialect } from '../../../src/storage/sql-dialect.js';
import type { DatabaseAdapter, AsyncConnectionManager } from '../../../src/storage/database-adapter.js';
import { DatabaseAdapterError } from '../../../src/storage/database-adapter.js';

describe('SqlDialect', () => {
  describe('factory methods', () => {
    it('sqlite() returns dialect with type "sqlite"', () => {
      const dialect = SqlDialect.sqlite();
      expect(dialect.type).toBe('sqlite');
    });

    it('postgresql() returns dialect with type "postgresql"', () => {
      const dialect = SqlDialect.postgresql();
      expect(dialect.type).toBe('postgresql');
    });

    it('instances are immutable (type is readonly)', () => {
      const dialect = SqlDialect.sqlite();
      expect(() => {
        (dialect as { type: string }).type = 'postgresql';
      }).toThrow();
    });
  });

  describe('JSON operations', () => {
    describe('jsonExtract', () => {
      it('SQLite: generates json_extract', () => {
        const d = SqlDialect.sqlite();
        expect(d.jsonExtract('data', '$.name')).toBe("json_extract(data, '$.name')");
      });

      it('SQLite: handles nested paths', () => {
        const d = SqlDialect.sqlite();
        expect(d.jsonExtract('data', '$.address.city')).toBe("json_extract(data, '$.address.city')");
      });

      it('PostgreSQL: generates ->> operator', () => {
        const d = SqlDialect.postgresql();
        expect(d.jsonExtract('data', '$.name')).toBe("data->>'name'");
      });

      it('PostgreSQL: extracts last key from nested path', () => {
        const d = SqlDialect.postgresql();
        expect(d.jsonExtract('data', '$.address.city')).toBe("data->>'city'");
      });
    });

    describe('jsonSet', () => {
      it('SQLite: generates json_set', () => {
        const d = SqlDialect.sqlite();
        expect(d.jsonSet('data', '$.name', "'Alice'")).toBe("json_set(data, '$.name', 'Alice')");
      });

      it('PostgreSQL: generates jsonb_set', () => {
        const d = SqlDialect.postgresql();
        expect(d.jsonSet('data', '$.name', "'Alice'")).toBe(
          "jsonb_set(data::jsonb, '{name}', to_jsonb('Alice'))"
        );
      });

      it('PostgreSQL: handles nested paths as array', () => {
        const d = SqlDialect.postgresql();
        expect(d.jsonSet('data', '$.address.city', "'NYC'")).toBe(
          "jsonb_set(data::jsonb, '{address,city}', to_jsonb('NYC'))"
        );
      });
    });

    describe('jsonEach', () => {
      it('SQLite: generates json_each', () => {
        const d = SqlDialect.sqlite();
        expect(d.jsonEach('tags')).toBe('json_each(tags)');
      });

      it('PostgreSQL: generates jsonb_array_elements', () => {
        const d = SqlDialect.postgresql();
        expect(d.jsonEach('tags')).toBe('jsonb_array_elements(tags)');
      });
    });
  });

  describe('date/time functions', () => {
    it('SQLite: now() returns datetime("now")', () => {
      const d = SqlDialect.sqlite();
      expect(d.now()).toBe("datetime('now')");
    });

    it('PostgreSQL: now() returns NOW()', () => {
      const d = SqlDialect.postgresql();
      expect(d.now()).toBe('NOW()');
    });

    it('both: currentTimestamp() returns CURRENT_TIMESTAMP', () => {
      expect(SqlDialect.sqlite().currentTimestamp()).toBe('CURRENT_TIMESTAMP');
      expect(SqlDialect.postgresql().currentTimestamp()).toBe('CURRENT_TIMESTAMP');
    });

    it('SQLite: datetimeAdd generates datetime with modifier', () => {
      const d = SqlDialect.sqlite();
      expect(d.datetimeAdd('created_at', 1, 'day')).toBe("datetime(created_at, '+1 day')");
    });

    it('PostgreSQL: datetimeAdd generates INTERVAL expression', () => {
      const d = SqlDialect.postgresql();
      expect(d.datetimeAdd('created_at', 1, 'day')).toBe("created_at + INTERVAL '1 day'");
    });

    it('SQLite: datetimeAdd with hours', () => {
      const d = SqlDialect.sqlite();
      expect(d.datetimeAdd('ts', 2, 'hour')).toBe("datetime(ts, '+2 hour')");
    });

    it('PostgreSQL: datetimeAdd with hours', () => {
      const d = SqlDialect.postgresql();
      expect(d.datetimeAdd('ts', 2, 'hour')).toBe("ts + INTERVAL '2 hour'");
    });
  });

  describe('DDL helpers', () => {
    it('SQLite: autoIncrement() returns AUTOINCREMENT', () => {
      expect(SqlDialect.sqlite().autoIncrement()).toBe('AUTOINCREMENT');
    });

    it('PostgreSQL: autoIncrement() returns GENERATED BY DEFAULT AS IDENTITY', () => {
      expect(SqlDialect.postgresql().autoIncrement()).toBe('GENERATED BY DEFAULT AS IDENTITY');
    });

    it('both: textType() returns TEXT', () => {
      expect(SqlDialect.sqlite().textType()).toBe('TEXT');
      expect(SqlDialect.postgresql().textType()).toBe('TEXT');
    });

    it('SQLite: jsonType() returns TEXT', () => {
      expect(SqlDialect.sqlite().jsonType()).toBe('TEXT');
    });

    it('PostgreSQL: jsonType() returns JSONB', () => {
      expect(SqlDialect.postgresql().jsonType()).toBe('JSONB');
    });

    it('SQLite: booleanType() returns INTEGER', () => {
      expect(SqlDialect.sqlite().booleanType()).toBe('INTEGER');
    });

    it('PostgreSQL: booleanType() returns BOOLEAN', () => {
      expect(SqlDialect.postgresql().booleanType()).toBe('BOOLEAN');
    });
  });

  describe('full-text search', () => {
    it('SQLite: creates FTS5 virtual table', () => {
      const d = SqlDialect.sqlite();
      expect(d.createFtsTable('search_idx', ['title', 'body'], 'articles')).toBe(
        'CREATE VIRTUAL TABLE search_idx USING fts5(title, body, content=articles)'
      );
    });

    it('SQLite: FTS5 without content table', () => {
      const d = SqlDialect.sqlite();
      expect(d.createFtsTable('search_idx', ['title', 'body'])).toBe(
        'CREATE VIRTUAL TABLE search_idx USING fts5(title, body)'
      );
    });

    it('PostgreSQL: creates materialized view with content table', () => {
      const d = SqlDialect.postgresql();
      expect(d.createFtsTable('search_idx', ['title', 'body'], 'articles')).toBe(
        'CREATE MATERIALIZED VIEW search_idx AS SELECT title, body FROM articles'
      );
    });

    it('PostgreSQL: materialized view without content table uses table name', () => {
      const d = SqlDialect.postgresql();
      expect(d.createFtsTable('search_idx', ['title', 'body'])).toBe(
        'CREATE MATERIALIZED VIEW search_idx AS SELECT title, body FROM search_idx'
      );
    });
  });

  describe('index helpers', () => {
    it('SQLite: creates json_extract index', () => {
      const d = SqlDialect.sqlite();
      expect(d.createJsonIndex('users', 'profile', '$.email')).toBe(
        "CREATE INDEX idx_users_profile ON users(json_extract(profile, '$.email'))"
      );
    });

    it('PostgreSQL: creates GIN index with jsonb_path_ops', () => {
      const d = SqlDialect.postgresql();
      expect(d.createJsonIndex('users', 'profile', '$.email')).toBe(
        'CREATE INDEX idx_users_profile ON users USING GIN(profile jsonb_path_ops)'
      );
    });
  });

  describe('parameterization', () => {
    it('SQLite: parameterize() always returns "?"', () => {
      const d = SqlDialect.sqlite();
      expect(d.parameterize(0)).toBe('?');
      expect(d.parameterize(1)).toBe('?');
      expect(d.parameterize(5)).toBe('?');
    });

    it('PostgreSQL: parameterize() returns 1-indexed positional params', () => {
      const d = SqlDialect.postgresql();
      expect(d.parameterize(1)).toBe('$1');
      expect(d.parameterize(2)).toBe('$2');
      expect(d.parameterize(3)).toBe('$3');
    });
  });

  describe('query helpers', () => {
    it('SQLite: ilike() returns LIKE', () => {
      expect(SqlDialect.sqlite().ilike()).toBe('LIKE');
    });

    it('PostgreSQL: ilike() returns ILIKE', () => {
      expect(SqlDialect.postgresql().ilike()).toBe('ILIKE');
    });

    it('SQLite: trueLiteral() returns "1"', () => {
      expect(SqlDialect.sqlite().trueLiteral()).toBe('1');
    });

    it('PostgreSQL: trueLiteral() returns "TRUE"', () => {
      expect(SqlDialect.postgresql().trueLiteral()).toBe('TRUE');
    });

    it('SQLite: falseLiteral() returns "0"', () => {
      expect(SqlDialect.sqlite().falseLiteral()).toBe('0');
    });

    it('PostgreSQL: falseLiteral() returns "FALSE"', () => {
      expect(SqlDialect.postgresql().falseLiteral()).toBe('FALSE');
    });

    it('SQLite: limitOffset with both limit and offset', () => {
      expect(SqlDialect.sqlite().limitOffset(10, 20)).toBe('LIMIT ? OFFSET ?');
    });

    it('SQLite: limitOffset with limit only', () => {
      expect(SqlDialect.sqlite().limitOffset(10)).toBe('LIMIT ?');
    });

    it('PostgreSQL: limitOffset with both limit and offset', () => {
      expect(SqlDialect.postgresql().limitOffset(10, 20)).toBe('LIMIT $1 OFFSET $2');
    });

    it('PostgreSQL: limitOffset with limit only', () => {
      expect(SqlDialect.postgresql().limitOffset(10)).toBe('LIMIT $1');
    });
  });
});

describe('DatabaseAdapter interface (structural type tests)', () => {
  function createMockAdapter(type: 'sqlite' | 'postgresql'): DatabaseAdapter {
    return {
      open: () => {},
      close: () => {},
      isOpen: () => false,
      query: () => [],
      exec: () => {},
      transaction: <T>(fn: () => T) => fn,
      asyncQuery: async () => [],
      asyncExec: async () => {},
      asyncTransaction: async <T>(fn: () => Promise<T>) => fn(),
      getDialect: () => type === 'sqlite' ? SqlDialect.sqlite() : SqlDialect.postgresql(),
      getType: () => type,
      healthCheck: async () => true,
      getPoolMetrics: () => ({ totalCount: 0, idleCount: 0, waitingCount: 0 }),
    };
  }

  it('requires all sync methods', () => {
    const adapter = createMockAdapter('sqlite');
    expect(typeof adapter.open).toBe('function');
    expect(typeof adapter.close).toBe('function');
    expect(typeof adapter.isOpen).toBe('function');
    expect(typeof adapter.query).toBe('function');
    expect(typeof adapter.exec).toBe('function');
    expect(typeof adapter.transaction).toBe('function');
  });

  it('requires all async methods', () => {
    const adapter = createMockAdapter('sqlite');
    expect(typeof adapter.asyncQuery).toBe('function');
    expect(typeof adapter.asyncExec).toBe('function');
    expect(typeof adapter.asyncTransaction).toBe('function');
  });

  it('requires getDialect() returning SqlDialect', () => {
    const adapter = createMockAdapter('sqlite');
    expect(typeof adapter.getDialect).toBe('function');
    const dialect = adapter.getDialect();
    expect(dialect).toBeInstanceOf(SqlDialect);
  });

  it('requires getType() returning string', () => {
    const adapter = createMockAdapter('sqlite');
    expect(typeof adapter.getType).toBe('function');
  });

  it('getType() returns sqlite or postgresql', () => {
    const sqliteAdapter = createMockAdapter('sqlite');
    const pgAdapter = createMockAdapter('postgresql');
    expect(sqliteAdapter.getType()).toBe('sqlite');
    expect(pgAdapter.getType()).toBe('postgresql');
  });

  it('getDialect() returns matching dialect type', () => {
    const sqliteAdapter = createMockAdapter('sqlite');
    const pgAdapter = createMockAdapter('postgresql');
    expect(sqliteAdapter.getDialect().type).toBe('sqlite');
    expect(pgAdapter.getDialect().type).toBe('postgresql');
  });
});

describe('AsyncConnectionManager interface (structural type tests)', () => {
  function createMockAsyncConn(): AsyncConnectionManager {
    return {
      open: async () => {},
      close: async () => {},
      isOpen: () => false,
      query: async () => [],
      exec: async () => {},
      transaction: async <T>(fn: () => Promise<T>) => fn(),
    };
  }

  it('requires async open/close', () => {
    const conn = createMockAsyncConn();
    expect(typeof conn.open).toBe('function');
    expect(typeof conn.close).toBe('function');
    expect(typeof conn.isOpen).toBe('function');
  });

  it('requires async query/exec/transaction', () => {
    const conn = createMockAsyncConn();
    expect(typeof conn.query).toBe('function');
    expect(typeof conn.exec).toBe('function');
    expect(typeof conn.transaction).toBe('function');
  });
});

describe('DatabaseAdapterError', () => {
  it('is an Error subclass', () => {
    const err = new DatabaseAdapterError('test');
    expect(err).toBeInstanceOf(Error);
    expect(err).toBeInstanceOf(DatabaseAdapterError);
  });

  it('has name "DatabaseAdapterError"', () => {
    const err = new DatabaseAdapterError('test');
    expect(err.name).toBe('DatabaseAdapterError');
  });

  it('preserves message', () => {
    const err = new DatabaseAdapterError('Async not supported on SQLite');
    expect(err.message).toBe('Async not supported on SQLite');
  });
});
